
ptl.py MCU_0 "Nvme task start"

ptl.py MCU_1 "SubSystem schedule start"
ptl.py MCU_1 "L1_TaskSchedule start"
ptl.py MCU_1 "L1 get scmd"
ptl.py MCU_1 "L1 proc special scmd"
ptl.py MCU_1 "L1 Buffer management"
ptl.py MCU_1 "L1 Cache search"
ptl.py MCU_1 "L1 cache management"
ptl.py MCU_1 "L1 Host IO"
ptl.py MCU_1 "L1 Merge Flush"
ptl.py MCU_1 "L1 Task Recycle"
ptl.py MCU_1 "L1_TaskSchedule end"
ptl.py MCU_1 "L1_NvmeBuildDSG"
ptl.py MCU_1 "L1_NvmeBuildHSG"
ptl.py MCU_1 "L1_NvmeBuild DRQ/DWQ"
ptl.py MCU_1 "L1_HostReadBuildBufReq start"
ptl.py MCU_1 "L1_HostReadBuildBufReq end"

ptl.py MCU_1 "L2_Schedule start"
ptl.py MCU_1 "L2 select PU"
ptl.py MCU_1 "L2 select Thread"
ptl.py MCU_1 "L2 FTL write"
ptl.py MCU_1 "FTL L2_LookupPMT start"
ptl.py MCU_1 "FTL L2_LookupPMT end"
ptl.py MCU_1 "L2 FTL read"
ptl.py MCU_1 "L2_DummyWrite start"
ptl.py MCU_1 "L2_DummyWrite end"
ptl.py MCU_1 "L2_FtlReadMerge start"
ptl.py MCU_1 "L2_FtlReadMerge end"
ptl.py MCU_1 "L2_FtlReadNormal start"
ptl.py MCU_1 "L2_FtlReadNormal end"
ptl.py MCU_1 "L3_SendFCmd start"
ptl.py MCU_1 "L3_SendFCmd end"
ptl.py MCU_1 "L2 FTL UpdateTablesBeforeWrite start"
ptl.py MCU_1 "L2 FTL UpdateTablesBeforeWrite end"
ptl.py MCU_1 "L2_PopReadBufREQ start"
ptl.py MCU_1 "L2_PopReadBufREQ end"
ptl.py MCU_1 "L2_FTLEntry end"
ptl.py MCU_1 "L2_FTLThreadDecision end"
ptl.py MCU_1 "L2_FtlWriteNormal end"

ptl.py MCU_2 "L3_PopFCmdQ start"

ptl.py MCU_2 "L3_PopFCmdQ end"
ptl.py MCU_2 "L3_PCmdHandling end"
ptl.py MCU_2 "L3_ProcRecycle end"
ptl.py MCU_2 "L3_SelectTLun end"

ptl.py MCU_2 "L3_AdapterFCmdEntry start"
ptl.py MCU_2 "L3_AdapterFCmdEntry end"
ptl.py MCU_2 "L3_SetNFCQEntry end"
ptl.py MCU_2 "L3_SetPRCQEntry end"
ptl.py MCU_2 "L3_TriggerNFC end"
ptl.py MCU_2 "L3_UpdateFCmdEntryMonitor end"
ptl.py MCU_2 "L3_SetFCmdRPtr end"
