/*******************************************************************************
* Copyright (C), 2015 VIA Technologies, Inc. All Rights Reserved.              *
*                                                                              *
* This PROPRIETARY SOFTWARE is the property of VIA Technologies, Inc.          *
* and may contain trade secrets and/or other confidential information of VIA   *
* Technologies,Inc.                                                            *
* This file shall not be disclosed to any third party, in whole or in part,    *
* without prior written consent of VIA.                                        *
*                                                                              *
* THIS PROPRIETARY SOFTWARE AND ANY RELATED DOCUMENTATION ARE PROVIDED AS IS,  *
* WITH ALL FAULTS, AND WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS OR IMPLIED, *
* AND VIA TECHNOLOGIES, INC. DISCLAIMS ALL EXPRESS OR IMPLIED WARRANTIES OF    *
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR        *
* NON-INFRINGEMENT.                                                            *
********************************************************************************
Filename    : HAL_FlashCmd.c
Version     : Ver 1.0
Author      : peter
Date        : 2012.01.08
Description : this file encapsulate PRCQ CMD relative interface definitions.
Others      : This file's flash cmd is for TLC/SLC 2Pln.
Modify      :
20140904    tobey     uniform code style and wipe off unrelative code
20150604    steven    add TLC flash cmd
20160210    abby      modify to meet VT3533
*******************************************************************************/
#include "HAL_FlashCmd.h"

GLOBAL MCU12_VAR_ATTR volatile NFC_PRCQ_QE *g_pNfcPRCQQe;
GLOBAL MCU12_VAR_ATTR volatile NFC_PRCQ_QE_EXT *g_pNfcPRCQQeExt;

/* PRCQ One Phase Cmd Element entry */
/* Group0, for write and erase cmd  */
GLOBAL MCU12_DRAM_TEXT U8 g_aCQE1E[QE_CMD_GROUP_DEPTH] = 
{
    0xEF,0xFA,0xFF,0x03,
    0x90,0x00,0x30,0x60,
    0xEE,0x31,0x3F,0xFC,
    0x09,0x01,0x02,0xA2
};

#if 0//extend for future
/* Group1, for read and other cmd  */
GLOBAL MCU12_DRAM_TEXT U8 g_aCQE1EExt[QE_CMD_GROUP_DEPTH] =
{
    0xEF,0xFA,0xFF,0x03,
    0x90,0x00,0x30,0x60,
    0xEE,0x31,0x3F,0xFC,
    0x09,0x01,0x02,0xA2
};
#endif
/* PRCQ Two Phase Cmd Element entry */
/* Group0, for write and erase cmd  */
GLOBAL MCU12_DRAM_TEXT U16 g_aCQE2E[QE_CMD_GROUP_DEPTH] =
{
    0x3000,0x1080,0x1181,0xD060,
    0x1180,0x1a85,0xe005,0x1085,
    0x3060,0x1580,0x3200,0x3100,
    0x3C60,0x1581,0x1A80,0x1185
};
#if 0//extend for future
/* Group1, for read and other cmd  */
GLOBAL MCU12_DRAM_TEXT U16 g_aCQE2EExt[QE_CMD_GROUP_DEPTH] =
{
    0x3000,0x1080,0x1181,0xD060,
    0x1180,0x1a85,0xe005,0x1085,
    0x3060,0x1580,0x3200,0x3100,
    0x3C60,0x1581,0x1A80,0x1185
};
#endif

/* PRCQ Status Phase Cmd Element entry */
GLOBAL MCU12_DRAM_TEXT U16 g_aSQEE[QE_OPRATION_GROUP_DEPTH] =
{
    0x3E70,0x2E70,0x3d70,0x0E70,
    0xbe70,0x3d78,0x2E78,0x3E78
};

/* PRCQ table */
GLOBAL MCU12_VAR_ATTR PRCQ_TABLE g_aPrcqTable[FLASH_PRCQ_CNT] =
{
    /* normal cmd's */
    {FLASH_PRCQ_RESET,                   NF_NORMAL_CMD,  TRIG_CMD_OTHER,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_RESET_NOSTS,             NF_NORMAL_CMD,  TRIG_CMD_OTHER,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_RESET_LUN,               NF_NORMAL_CMD,  TRIG_CMD_OTHER,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_READID,                  NF_NORMAL_CMD,  TRIG_CMD_OTHER,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_SETFEATURE,              NF_NORMAL_CMD,  TRIG_CMD_WRITE,   INVALID_BIT(9),    0},
    /*  SLC 1PLN cmd  */
    {FLASH_PRCQ_ERS_1PLN,                NF_NORMAL_CMD,  TRIG_CMD_ERASE,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_READ_1PLN,               NF_NORMAL_CMD,  TRIG_CMD_READ,    INVALID_BIT(9),    0},
    {FLASH_PRCQ_PRG_1PLN,                NF_NORMAL_CMD,  TRIG_CMD_WRITE,   INVALID_BIT(9),    0}, 
    /*  TLC 1PLN cmd  */
    {FLASH_PRCQ_TLC_ERS_1PLN,            NF_NORMAL_CMD,  TRIG_CMD_ERASE,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_TLC_READ_LOW_PAGE_1PLN,  NF_NORMAL_CMD,  TRIG_CMD_READ,    INVALID_BIT(9),    0},
    {FLASH_PRCQ_TLC_READ_MID_PAGE_1PLN,  NF_NORMAL_CMD,  TRIG_CMD_READ,    INVALID_BIT(9),    0},
    {FLASH_PRCQ_TLC_READ_UPP_PAGE_1PLN,  NF_NORMAL_CMD,  TRIG_CMD_READ,    INVALID_BIT(9),    0},    
    {FLASH_PRCQ_TLC_1ST_PRG_1PLN,        NF_NORMAL_CMD,  TRIG_CMD_WRITE,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_CHANGEREADCOLUM_1PLN,    NF_NORMAL_CMD,  TRIG_CMD_READ,    INVALID_BIT(9),    0},
#ifndef BOOTLOADER
    /*  SLC FULL PLN cmd, 15nm TSB is 2 PLN flash  */
    {FLASH_PRCQ_ERS_FULL_PLN,            NF_NORMAL_CMD,  TRIG_CMD_ERASE,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_READ_FULL_PLN,           NF_NORMAL_CMD,  TRIG_CMD_READ,    INVALID_BIT(9),    0}, 
    {FLASH_PRCQ_PRG_FULL_PLN,            NF_NORMAL_CMD,  TRIG_CMD_WRITE,   INVALID_BIT(9),    0},
    /*  TLC FULL PLN cmd, 15nm TSB is 2 PLN flash  */
    {FLASH_PRCQ_TLC_ERS_FULL_PLN,              NF_NORMAL_CMD,  TRIG_CMD_ERASE,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_TLC_READ_LOW_PAGE_FULL_PLN,    NF_NORMAL_CMD,  TRIG_CMD_READ,    INVALID_BIT(9),    0},
    {FLASH_PRCQ_TLC_READ_MID_PAGE_FULL_PLN,    NF_NORMAL_CMD,  TRIG_CMD_READ,    INVALID_BIT(9),    0},
    {FLASH_PRCQ_TLC_READ_UPP_PAGE_FULL_PLN,    NF_NORMAL_CMD,  TRIG_CMD_READ,    INVALID_BIT(9),    0},
    {FLASH_PRCQ_TLC_1ST_PRG_FULL_PLN,          NF_NORMAL_CMD,  TRIG_CMD_WRITE,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_CHANGEREADCOLUM_FULL_PLN,      NF_NORMAL_CMD,  TRIG_CMD_READ,    INVALID_BIT(9),    0},

    {FLASH_PRCQ_GETFEATURE,                    NF_NORMAL_CMD,  TRIG_CMD_OTHER,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_READ_STS_ENHANCE,              NF_NORMAL_CMD,  TRIG_CMD_OTHER,   INVALID_BIT(9),    0}, 
#endif
    /* pio cmd, unit in DW*/
    {FLASH_PRCQ_PIO_SETFEATURE,                NF_PIO_CMD,        TRIG_CMD_OTHER,   INVALID_BIT(9),    0},
    {FLASH_PRCQ_PIO_SETFEATURE_EX,             NF_PIO_CMD,        TRIG_CMD_OTHER,   INVALID_BIT(9),    0}
};

/* normal cmd PRCQ QE */
GLOBAL MCU12_DRAM_TEXT U8 l_aQETable[] =
{
    // FLASH_PRCQ_RESET 
    // FF  | bsy | finish
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_FF),
    QE_GRP_ATTR(PRCQ_READ_STATUS)       |QE_INDEX(SQEE_3E70),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_RESET_NOSTS
    // FF  | finish
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_FF),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_RESET_LUN
    // FA | ADDR  | bsy | finish
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_FA),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS)       |QE_INDEX(SQEE_3E70),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),
    
    //FLASH_PRCQ_READID
    // 90 | addr x 1 | reg read |finish
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_90),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_ADDR)    |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_REG_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_SETFEATURE
    // ef | addr x 1 | data(reg write) | finish
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_EF),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_ADDR)    |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_REG_WRITE)         |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    /* SLC SINGLE */
    // FLASH_PRCQ_ERS_1PLN
    // A2 |60 | addr X 3 (row addr) | d0 | bsy | finish
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_A2),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_D060),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_READ_1PLN
    // A2 | 00 | addr x 5 | 30  | bsy | 00 | addr x 5 | 05 | addr x 5 | E0 | data (pln0) | finish 
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_A2),  
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3100),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),  
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(RETURN),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(JUMP),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SKIP),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_3F),
#else
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_PRG_1PLN
    // A2 | 80 |ADD[0] X 5 | Data pln 0 |10 | BSY| 10| BSY |END 
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_A2),
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1580),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT_W),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3D78),
#else
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1080),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR0),
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    /*  TLC 1PLN  */
    // FLASH_PRCQ_TLC_ERS_1PLN
    // 60h-Addrx3-D0h-->tBERASES-->Finish
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_D060),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),
    
    /*
    TLC Read With Data Out:
    01h/02h/03h-00h-Addrx3-30h-->tR1-->
    05h-Addrx5-E0h-->DataOut-->Finish
    */
    // FLASH_PRCQ_TLC_READ_LOW_PAGE_1PLN
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_01),
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3100),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),  
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(RETURN),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(JUMP),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SKIP),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_3F),
#else
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),  
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),

    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_TLC_READ_MID_PAGE_1PLN
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_02),
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3100),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),  
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(RETURN),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(JUMP),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SKIP),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_3F),
#else
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),  
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_TLC_READ_UPP_PAGE_1PLN
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_03),
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3100),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),  
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(RETURN),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(JUMP),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SKIP),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_3F),
#else
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),  
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),

    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_TLC_1ST_PRG_1PLN
    /* 3 Physical PAGE TLC 1st Program with data in*/
    /*
    1st Program lower page part with data in:
    01h-80h-Addrx5-DataIn-1Ah-->tCBSY1-->Finish
    1st Program middle page part with data in:
    02h-80h-Addrx5-DataIn-1Ah-->tCBSY1-->Finish
    1st Program upper page part with data in:
    03h-80h-Addrx5-DataIn-10h-->tPROG-->Finish
    */
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_01),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1A80),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_02),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1A80),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),

    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_03),
#if 0//def FLASH_CACHE_OPERATION//patch for 1 plane cache write fail, pending
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1580),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT_W),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3D78),
#else
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1080),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR0),
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_CHANGEREADCOLUM_1PLN
    // 05 | addr x 2 (col addr)|e0        | data (pln 0) | finish
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_00),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_COL_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

#ifndef BOOTLOADER    
    /*SLC FULL*/
    // FLASH_PRCQ_ERS_FULL_PLN
    // A2 60 | RowAdd X 3 | 60 | RowAdd X 3 | D0 | BSY|END
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_A2),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_60),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_D060),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
    
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_READ_FULL_PLN
    // A2 60 | Addr 5 |60| Addr 5 |30|BSY |
    // 06|ADD X5 |e0|Data pln 0|
    // 06|ADD X5 |e0|Data pln 1|   END
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_A2),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_60),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3060),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3C60),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(RETURN),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(JUMP),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SKIP),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_3F),
#else
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3060),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),

    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_PRG_FULL_PLN
    // A2 80|ADD[0] X 5 | Data pln 0 |11 | BSY| 80 |ADD[1] X 5 | Data pln 1 | 10| BSY |END
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_A2),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1180),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1580),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR1),
    
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT_W),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3D78),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT_W),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3D78),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),    
#else
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1080),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),    
#endif

    // FLASH_PRCQ_TLC_ERS_FULL_PLN
    /* 60h-Addrx3EpP0-60h-Addrx3OpP0-60h-Addrx3EpP1-60h-Addrx3OpP1-D0h-->tBERASES-->Finish */
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_60),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_D060),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    /*
    TLC Read full plane With Data Out:
    01h/02h/03h-60h-Addrx3P0-
    01h/02h/03h-60h-Addrx3P1-30h-->tR1-->
    05h-Addrx5P0-E0h-->DataOutP0-->05h-Addrx5P1-E0h-->DataOutP1-->Finish
    */
    // FLASH_PRCQ_TLC_READ_LOW_PAGE_FULL_PLN 
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_01),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3200),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_01),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3100),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(RETURN),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(JUMP),

    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SKIP),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_3F),
#else
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_01),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_60),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_01),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3060),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),

    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_TLC_READ_MID_PAGE_FULL_PLN
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_02),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3200),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_02),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT),    
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3100),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(RETURN),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(JUMP),

    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SKIP),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_3F),
#else
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_02),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_60),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_02),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3060),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),

    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_TLC_READ_UPP_PAGE_FULL_PLN
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_03),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3200),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_03),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3000),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3100),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(RETURN),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(JUMP),

    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SKIP),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_3F),
#else
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_03),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_60),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_03),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_3060),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),

    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    /* 6 Physical PAGE TLC 1st Program with data in*/
    /*
    1st Program lower page part with data in:
    01h-80h-Addrx5P0-DataInP0-11h-->tCBSY1-->
    01h-80h-Addrx5OpP1-DataInP1-1Ah-->tCBSY1-->Finish
    */
    /*
    1st Program middle page part with data in:
    02h-80h-Addrx5P0-DataInP0-11h-->tCBSY1-->
    02h-80h-Addrx5P1-DataInP1-1Ah-->tCBSY1-->Finish
    */
    /*
    1st Program upper page part with data in:
    03h-80h-Addrx5P0-DataInP0-11h-->tCBSY1-->
    03h-80h-Addrx5P1-DataInP1-10h-->tCBSY1-->Finish
    */
    //FLASH_PRCQ_TLC_1ST_PRG_LOW_PAGE_PLN
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_01),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1180),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),

    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_01),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1A80),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),

    //FLASH_PRCQ_TLC_3RD_PRG_MID_PAGE_2PLN
#ifdef PATCH_HW_TLC_ROWADDR_SET
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_02),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1180),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR2),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR2),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR2),

    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_02),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1A80),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR3),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR3),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR3),
#else
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_02),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1180),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),

    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_02),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1A80),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
#endif

    //FLASH_PRCQ_TLC_3RD_PRG_UPP_PAGE_2PLN
#ifdef PATCH_HW_TLC_ROWADDR_SET
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_03),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1180),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR4),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR4),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR4),

    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_03),
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1580),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR5),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR5),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT_W),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3D78),
#else   
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1080),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR5),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR5),
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR4),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR5),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),
#else
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_03),
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1180),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_2E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),

    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_03),
#ifdef FLASH_CACHE_OPERATION
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1580),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(SELECT_W),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3D78),
#else   
    QE_GRP_ATTR(PRCQ_THREE_PHASE_CMD)   |QE_INDEX(CQE2E_1080),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_DMA_WRITE)         |QE_INDEX(ADDR1),
#endif
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),
#endif

    // FLASH_PRCQ_CHANGEREADCOLUM_FULL_PLN
    // 00 5x addr 05 2x addr e0  data
    // 00 5x addr 05 2x addr e0  data
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_00),    
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR0),    
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),    
    QE_GRP_ATTR(PRCQ_COL_ADDR)          |QE_INDEX(ADDR0), 
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR0),  
    
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_00),
    QE_GRP_ATTR(PRCQ_FIVE_CYCLE_ADDR)   |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_TWO_PHASE_CMD)     |QE_INDEX(CQE2E_E005),
    QE_GRP_ATTR(PRCQ_COL_ADDR)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_IDLE)              |QE_INDEX(1),  
    QE_GRP_ATTR(PRCQ_DMA_READ)          |QE_INDEX(ADDR1),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // FLASH_PRCQ_GETFEATURE
    // EE | ADDR X1 |BSY |DATA(REG READ) |FINISH
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_EE),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_ADDR)    |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_READ_STATUS)       |QE_INDEX(SQEE_3E70),
    QE_GRP_ATTR(PRCQ_ONE_CYCLE_CMD)     |QE_INDEX(CQE1E_00),
    QE_GRP_ATTR(PRCQ_REG_READ)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END),

    // NF_PRCQ_READ_STS_ENHANCE_1PLN
    QE_GRP_ATTR(PRCQ_READ_STATUS_EH)    |QE_INDEX(SQEE_3E78),
    QE_GRP_ATTR(PRCQ_ROW_ADDR)          |QE_INDEX(ADDR0),
    QE_GRP_ATTR(PRCQ_FINISH)            |QE_INDEX(END)
#endif
};

/* pio cmd PRCQ QE */
GLOBAL MCU12_DRAM_TEXT U32 l_aPioCmdTable[] = 
{
    //FLASH_PRCQ_PIO_SETFEATURE   
    RAW_PIO_CMD|PIO_CFG_VALUE(0xef),
    RAW_PIO_ADDR|PIO_CFG_VALUE(0x10),
    RAW_PIO_DATAOUT|PIO_CFG_VALUE(0x6),
    RAW_PIO_DATAOUT|PIO_CFG_VALUE(0x0),
    RAW_PIO_DATAOUT|PIO_CFG_VALUE(0x0),
    RAW_PIO_DATAOUT|PIO_CFG_VALUE(0x0)|RAW_PIO_IO_LAST_PHS(1),  

    //FLASH_PRCQ_PIO_SETFEATURE_EX
    RAW_PIO_CMD|PIO_CFG_VALUE(0xef),
    RAW_PIO_ADDR|PIO_CFG_VALUE(0x80),
    RAW_PIO_DATAOUT|PIO_CFG_VALUE(0x0),
    RAW_PIO_DATAOUT|PIO_CFG_VALUE(0x0),
    RAW_PIO_DATAOUT|PIO_CFG_VALUE(0x0),
    RAW_PIO_DATAOUT|PIO_CFG_VALUE(0x0)|RAW_PIO_IO_LAST_PHS(1)  
};

/*------------------------------------------------------------------------------
Name: HAL_NfcQEEInit
Description:
    Initialize PRCQ QE area. including 1 cycle cmd group, 2 cycle cmd group
    and operation group, details refer to PRCQ spec.
Input Param:
    none
Output Param:
    none
Return Value:
    none
Usage:
    invoked in BootLoader or FW. PRCQ QE area may be different between BootLoader and FW.
History:
    20140902    tobey   uniform coding style.
------------------------------------------------------------------------------*/
void MCU12_DRAM_TEXT HAL_NfcQEEInit(void)
{
    U32 ulQeIndex;

    for (ulQeIndex = 0; ulQeIndex < QE_CMD_GROUP_DEPTH; ulQeIndex++)
    {
        g_pNfcPRCQQe->aPRCQ_CQE1E[ulQeIndex] = g_aCQE1E[ulQeIndex];
        g_pNfcPRCQQe->aPRCQ_CQE2E[ulQeIndex] = g_aCQE2E[ulQeIndex];
    }
    //extend CQEE, add in 533
    for (ulQeIndex = 0; ulQeIndex < QE_CMD_GROUP_DEPTH; ulQeIndex++)
    {
        g_pNfcPRCQQeExt->aPRCQ_CQE1E[ulQeIndex] = g_aCQE1E[ulQeIndex];//g_aCQE1EExt[ulQeIndex];//extend for future
        g_pNfcPRCQQeExt->aPRCQ_CQE2E[ulQeIndex] = g_aCQE2E[ulQeIndex];//g_aCQE2EExt[ulQeIndex];//extend for future
    }
    for (ulQeIndex = 0; ulQeIndex < QE_OPRATION_GROUP_DEPTH; ulQeIndex++)
    {
        g_pNfcPRCQQe->aPRCQ_SQEE[ulQeIndex] = g_aSQEE[ulQeIndex];
    }

    return;
}

/*------------------------------------------------------------------------------
Name: HAL_NfcPrcqInit
Description: 
    Fill PRCQ sequency of all cmd into SRAM 
Input Param:
    none
Output Param:
    none
Return Value:
    none
Usage:
    invoked in BootLoader or FW. PRCQ QE area may be different between BootLoader and FW.
History:
    20151027    abby create.
------------------------------------------------------------------------------*/
void MCU12_DRAM_TEXT HAL_NfcPrcqInit(void)
{
    U32 ulQeCnt = 0;
    U32 ulPioQeCnt = 0;
    U8 ucCmdCodeIndex = 0;
    
    /*  g_pNfcPRCQ ->PRCQ_ENTRY_BASE  */
    volatile U8 *pNfcQe = (volatile U8 *)g_pNfcPRCQ;
    
    /*  fill every QE into SRAM align in byte unit  */
    for (ucCmdCodeIndex = 0; ucCmdCodeIndex < FLASH_PRCQ_NON_PIO_NUM; ucCmdCodeIndex++)
    {
        do
        {
            *pNfcQe = l_aQETable[ulQeCnt];
            pNfcQe++;
            ulQeCnt++;

        }while ((QE_GRP_ATTR(PRCQ_FINISH)|QE_INDEX(END)) != l_aQETable[ulQeCnt-1]);
        /*  align in DW    */
        pNfcQe = (volatile U8 *)ALIGN_IN_DW((U32)((U32 *)pNfcQe));
    }
    
    /*  continue to fill PIO QE into SRAM by DW align  */
    g_pNfcPRCQ = (U32 *)pNfcQe;
    
    for (ucCmdCodeIndex = FLASH_PRCQ_NON_PIO_NUM; ucCmdCodeIndex < FLASH_PRCQ_CNT; ucCmdCodeIndex++)
    {
        do
        {
            *g_pNfcPRCQ = l_aPioCmdTable[ulPioQeCnt];
            g_pNfcPRCQ++;
            ulPioQeCnt++;

        } while ( RAW_PIO_IO_LAST_PHS(1) != (l_aPioCmdTable[ulPioQeCnt-1] & (0x1 << 31)) );
    }
    
    return;
}

/*------------------------------------------------------------------------------
Name: HAL_NfcPrcqTableInit
Description: 
    Initialize PRCQ table. specially bsQEPhase and bsQEPtr.
Input Param:
    none
Output Param:
    none
Return Value:
    none
Usage:
    invoked by HAL_NfcInterfaceInitBasic().
History:
    20140902    tobey   uniform coding style.
    20151105    abby    modify to meet VT3533
------------------------------------------------------------------------------*/
void MCU12_DRAM_TEXT HAL_NfcPrcqTableInit(void)
{
    U8  ucCmdCodeIndex = 0;
    U32 ulPrcqDwCnt = 0;
    U32 ulByteCnt = 0;  //record byte location of normal cmd PRCQ
    U32 ulQECnt = 0;    //record QE number of normal cmd PRCQ
    U32 ulPioQECnt = 0;
    U32 ulBasePioStartDw = 0;

    /*  init normal cmd: 1 byte for 1 QE, need to align in DW    */
    for (ucCmdCodeIndex = 0; ucCmdCodeIndex < FLASH_PRCQ_NON_PIO_NUM; ucCmdCodeIndex++)
    {
        /*  get start PRCQ DW of this cmdCode   */
        g_aPrcqTable[ucCmdCodeIndex].bsPRCQStartDw = ulPrcqDwCnt;
        
        /*  ACC QE and byte number  */
        do 
        {
            ulByteCnt++;
            ulQECnt++;
        }while ( (QE_GRP_ATTR(PRCQ_FINISH)|QE_INDEX(END)) != l_aQETable[ulQECnt-1] );

        /* align in DW  */
        ulByteCnt = ALIGN_IN_DW(ulByteCnt);

        /*  Get next cmd start DW  */
        ulPrcqDwCnt = ulByteCnt / sizeof(U32);
    }

    /*  Set a base DW for ACC to avoid ulPioQECnt over l_aPioCmdTable[] definition*/
    ulBasePioStartDw = ulPrcqDwCnt;
    
    /*  init PIO cmd: 1 DW for 1 PIO QE, don't need to align in DW    */
    for (ucCmdCodeIndex = FLASH_PRCQ_NON_PIO_NUM; ucCmdCodeIndex < FLASH_PRCQ_CNT; ucCmdCodeIndex++)
    {
        /*  get start PRCQ DW of PIO cmdCode  */
        g_aPrcqTable[ucCmdCodeIndex].bsPRCQStartDw = ulBasePioStartDw + ulPioQECnt;
        
        /*  ACC PIO QE number  */
        do
        {
            ulPioQECnt++;
        }while (RAW_PIO_IO_LAST_PHS(1) != (l_aPioCmdTable[ulPioQECnt-1]&(0x1<<31)) );
                
        ulPrcqDwCnt = ulPioQECnt + ulBasePioStartDw;
    }

    return;
}

/*------------------------------------------------------------------------------
Name: HAL_NfcGetPrcqStartDw
Description: 
    get a prcq entry start DW;
    fuction instr put into SRAM
Input Param:
    U8 ucCmdType: equal to cmdcode in g_aPrcqTable.
Output Param:
    None
Return Value:
    PRCQ Start Dw
Usage:
    FW call this function to get a prcq start DW location for NFCQ.
History:
    20151028    abby   create.
------------------------------------------------------------------------------*/
U32 HAL_NfcGetPrcqStartDw(U8 ucCmdCode)
{
    return g_aPrcqTable[ucCmdCode].bsPRCQStartDw;
}

/* end of file HAL_FlashCmd.c */

